import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/header/header";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Sujin Jung Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body className={``}>
        <Header />
        {children}
      </body>
    </html>
  );
}
